---
- name: PreInstall
  yum: name={{ item }} state=installed
  with_items: 
    - libselinux-python

- name: Remove MariaDB ver 5.5
  yum: state=removed name=mariadb-server
  yum: state=removed name=mariadb-libs
- name: copy pero file
  template: src=MariaDB.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo

- name: Install MariaDB 
  yum: name={{ item }} state=installed
  with_items: 
    - MariaDB-server
    - MariaDB 
    - MySQL-python
  notify:
     - Start MySQL Server

  
- name: Ensure Service is Started and Enabled
  service: name=mysql state=started enabled=yes
  sudo: yes
    
- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
       - "{{ ansible_hostname|lower() }}"
       - 127.0.0.1
       - ::1
       - localhost
  when: mysql_root_db_pass != ''
    
#- name: Change passwords to root user
#  mysql_user: name=root host={{ item }} password={{ root_db_password }}
#  with_items:
#  - 127.0.0.1
#  - ::1
#  - localhost


#- name: ensure anonymous users are not in the database
#  mysql_user: name='' host={{ item }} state=absent
#  with_items:
#   - localhost
#   - "{{ ansible_hostname|lower() }}"

- name: remove the test database
  mysql_db: name=test state=absent




